### ISSUE TITLE
inject bytecode 

### ISSUE THREAD

**Issue by WithLin** [polterguy/lizzie#1]
I want to inject some code, but not in the Attribute way, because I want to inject some clients, such as rabbitmq, or redis dll inside the method etc , these dlls, I can not use the Attribute method, I want to pass the namespace and the classes and methods, then to the current framework, the framework helps me find him, then do before and after.can lizzie   do?

**Comment by polterguy** [comment]
Hmm, not entirely sure what you are trying to accomplish.It sounds like you are trying to `Bind` to a class you can't change for some reasons, am I right?

If I am right, maybe you could use the `binder["xxx"] = ...` method, and then simply forward the method to your _"closed class"_ ...?

Below is an example from the documentation ...

```csharp
using System;
using lizzie;

class MainClass
{
    public static void Main(string[] args)
    {
        // Some inline Lizzie code.
        var code = "foo()";

        // Creating a lambda function from our code.
        var function = Compiler.Compile<MainClass>(new Tokenizer(new LizzieTokenizer()), code);

        // Creating an instance of our class, which we can bind to our code.
        var context = new MainClass();

        // Creating a binder, and adding the 'foo' function to it.
        var binder = new Binder<MainClass>();
        binder["foo"] = new Function<MainClass>((ctx, binder2, arguments) => {
            Console.WriteLine("Hello World");
            return null;
        });

        // Evaluates our Lizzie code making sure we bind it to our instance.
        function(context, binder);

        // Waiting for user input.
        Console.Read();
    }
}
```

**Comment by WithLin** [comment]
thank you for your answer.but I still don't quite understand.
```c#
public class Person
{
        public void SayHello(string name)
        {
            Console.WriteLine(name);
        }
 }
```
i want to intercept  SayHello method.
as i said that i give the (namespace +the classes +methods) string to lizzie ,
which inject some IL.
```C#
 httpClient.GetAsync("http://localhost:5002/api/values");
var content = httpClient.GetAsync("http://localhost:5003/api/values");
```
When the user use httpclient,i want intercept some method inject header,which 
I want to pass some associated id.
From service A to service B.
this is a kind of interception scene, I also want to intercept rabbitmq, also injected into the headers.
can you understand my thoughts?

**Comment by polterguy** [comment]
> can you understand my thoughts?

Hmm, not entirely. If you try to create an example use case, from A to Z, describing what you're trying to achieve, it would be easier for me ...

But if I am to guess, you've got some existing code that you can't change, and as this existing code is being evaluated, you want something to happen before the original code is being executed, kind of in an AOP fashion, right ...?

If I am right, I assume your `SayHello` method, and its `Person` class are code you can't change, right ...?

Please realise that Lizzie doesn't _"inject IL"_. Maybe you'll have some _"aha moments"_ if you [check out its 'compiler', which is only 400 lines of code](https://github.com/polterguy/lizzie/blob/master/lizzie/Compiler.cs#L86).

The way Lizzie works, is that it creates a delegate for you, which is simply a list of other delegates, that each will do a _"lookup"_ into a `Dictionary`, using the _"Symbolic Name"_ (function name) as the key. This Dictionary returns a delegate, that becomes evaluated as you evaluate a Lizzie function. Below is pseudo code illustrating arguably the entire _"programming language"_.

```csharp
Dictionary<string, function> _keywords;
```

So when I write ...

```javascript
foo(57)
```

... as Lizzie code. This will retrieve the _"function"_ from my dictionary with the key of _"foo"_, and pass in 57 as an argument to that delegate ...

Lizzie is hence in such a regard arguably _"weird"_, since it neither compiles nor interprets your code. Instead Lizzie will use your functions as lookups into a `Dictionary`, which contains your _"keywords"_. This implies that if you are 100% certain of that you actually want to inject IL code into your assembly, then Lizzie is not your tool. However, as I started out with, if you give me your entire use case, from A to Z, I might find an alternative solution, which doesn't imply modifying the actual assembly at runtime ...

**Comment by WithLin** [comment]
well,Thank you for your answer. i understand it.

**Comment by polterguy** [comment]
NP. To be honest with you, I don't know what to call the process myself. It's not interpretation, since the end result is a delegate you can evaluate, that does not in any ways require the existing code, or interpret it in any ways. It is also not really a compilation process either, since it doesn't create an _"image"_ such as the C# compiler that creates a IL image you can execute. At some point I played around with referring to it as _"transpilation"_, but that's not accurate either, since transpilation translates from one language to another, and although arguably I do translate from Lizzie syntax to IL syntax, the process is very much _"indirect"_.

If you have any suggestions for what I should actually refer to the process as, feel free to come up with some :)

**Comment by spadino** [comment]
"Assemble"? "Collating"?

**Comment by polterguy** [comment]
Thank you @spadino but I think it's too late to change the name of the methods themselves since it would break existing code out there, but these are good suggestions for the documentation parts I think :)
