### ISSUE TITLE
Arguments to Any (and All) function call look wrong

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#11]
In Functions.Any, when the argument is a function, the function is called with the arguments of the current invocation (the arguments to Any). That seems wrong; I was expecting the function call to have its own arguments. What am I missing?

**Comment by polterguy** [comment]
Check up the documentation about the `@` token, it's equivalent to the (quote xxx) or the single tick token from Lisp. If it still doesn't make sense, let me know ...

If it makes sense, please close this one ...

[Docs about the @ character](https://github.com/polterguy/lizzie/blob/master/docs/introduction.md#whats-with-the-funny--symbol)

**Comment by polterguy** [comment]
OK, now I understand what you mean here. If you take a a look at Compiler.cs line 373, you'll see that the arguments used for the actual function implementation are `arguments`, which are determined during compilation, and not the `args` which are the `arguments` passed in from `Any`.

This is a necessary additional level of indirection to make sure arguments are _"applied"_ (evaluated), in cases where an argument is itself in fact a function invocation.

At the same time we don't really want to _"apply"_ an argument unless it's absolutely necessary (such as when it never needs to be evaluated, due to e.g. short circuit conditions).

I realise this is not my _"strongest"_ and most _"easily understood"_ parts of the code, and I believe it could be significantly simplified, to make it more easily understood, but I am pretty certain that from a functional point of view it works as expected ...

Basically, the `arguments` passed in from `Functions.Any` are never used. However, since all methods needs an argument instance, to have the correct signature, I simply chose to pass in the existing one, since although the method invocation never really uses these arguments, the method **signature** requires them to be there.

However, I changed it to make it more readable and less confusing to pass in an empty instance `new Arguments()` to avoid (some of the) existing confusion ...

I also chose to change it in the `ApplyArguments` method to use a new instance. Technically, this would require instantiating a new object, invoking the CTOR, making it become (slightly) slower - However, I doubt you'd be able to actually measure this, and I believe the clarity of code is worth it none the less, for reasons you pinpoint through your question ... :)
