### ISSUE TITLE
Return value of Add differs in LIst and Map cases

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#13]
When Add is used to put values on a list, then the return value is the last item added. When Add is used to put items into a map, the return value is the total number of items in the map after all insertions.

The inconsistency seems odd to me.

As I think about use cases, it seems like the "last value added" is more likely to be useful.

**Comment by polterguy** [comment]
Good point, you're going to completely eliminate my spare time this weekend :D

**Comment by polterguy** [comment]
I've changed this in the repo. Technically it is a breaking change, and I don't like making breaking changes unless I have to, but I very much agree with your argument, and I doubt there will be any problems due to it - So I chose to do it none the less.

Besides, until Lizzie is in >= version 1.0, I have kind of like the liberty to apply (some smaller) breaking changes I guess ... :)

However, `add` with a `map` type will now return the last value added, and in such a way have a similar interface to add with a `list`. I must confess, you have a very # eye ... ;)
