### ISSUE TITLE
Each throws away the results

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#16]
Functions.Each iterates over the list and computes a value ("current"), which it then throws away. This means that Each is only useful for side-effects. (Like writing objects to console.)

I was expecting a function more like javascript's "map" concept, where a sequence {a,b,c} is turned into {f(a), f(b), f(c)}. This would allow the Each function to be useful for side-effects and data transformations.

**Comment by polterguy** [comment]
Hmm ...

You could declare a list, or a map, before entering `each`. Maybe an additional function, which does what you suggest. Do you have any specific specification in mind for this ...?

Thank you for really diving into this BTW, I love (almost) all your ideas ... :)

**Comment by polterguy** [comment]
Done (in repo)!

This is definitely by far your smartest idea for a change to its actual logic, and definitely makes a lot of sense. Technically, it is a breaking change, since it changes the return value of `each`, but since the return value was the original collection, I doubt it'll break any code out there, since probably few if any would be interested in its old return value, and the features it provides are really cool :)

Technically, it makes the performance slightly slower, for consumption where you don't care about the transformation - But the ability to transform a list and/or map, into _"something else"_, is none the less definitely worth it!
