### ISSUE TITLE
Questions about CompileNumber

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#27]
Do you want "1e-5" to be a number? (I am asking because it does not contain a period, but would be a double. Hmmm... would 1e5 or 1e+5 be double or int?) Anyway: there are commonly accepted number formats that are not parsed by Lizzie.

Should Lizzie parse every number as double? I am leaning in that direction because the implementation of numeric operations has occasionally surprising behavior as it stands now due to integer/double arithmetic. For example: Divide(14, 8, 2.0) = (14 / 8) / 2.0 = 1 / 2.0 = 0.5. Or Modulo(17, 2.0) -> invalid operation exception.

This behavior seems OK when I write it out, but if function arguments were bound to variables then it would be mysterious.

Simply having everything in double would allow programmers to convert to int where they want by using a "floor" function, so the semantics would be clear.

**Comment by polterguy** [comment]
Well, the idea was to use exclusively double as numbers, since it eliminates a lot of problems,such as those pinpointed by you. It also makes it more closely resemble JavaScript, which although arguably have a lot of weaknesses, also occasionally has some very good ideas. And by sticking _"close"_ to JS, it becomes more intuitively understood by JS developers, which I believe is a strength for a lot of reasons ...

Regarding parsing of exponentials, such as _"1e-5"_, is fine for me, since I doubt there would be any edge cases where a potential conflict could occur, creating confusion. If you'd like to implement this, and the code quality is high, I would graciously accept a pull request for it :)

**Comment by polterguy** [comment]
The scientific notation suggestion here is a given I must confess, although I am not entirely sure about how to intelligently and automatically recognise all permutations of legal numbers. I assume it would require significantly expanding the `IsNumeric` method, in ways I don't entirely know how to, to accommodate for all possible permutations.

The _"all numbers should be double"_ part, although tempting, and actually my original design, I feel first of all is arguably _"too late"_, regardless of whether or not it's a good suggestion, since it would simply break too much existing code out there - Besides, I still _"feel"_ we need integer numbers.

I'll keep it open none the less to serve as a TODO for the scientific notation parts though ...

**Comment by robert-mccausland** [comment]
I've been having a look at Lizzie and would like to give the scientific notation feature a shot, would you like me to submit a PR for it? I haven't done open source before and wanted to get started with a relatively small project that I can get my head around. But I use C# a lot in my day job so the code quality hopefully won't be too bad :).

I think I can alter the `IsNumeric` method to accept strings that have exactly one 'e' or 'E', splitting on it and validating both parts. The first part would have the same validation as current and the second part would have to be a whole number (so no decimal) with an optional '+' or '-' preceding it. If there is no 'e' character present then it can be parsed like it is currently.

The scientific notation numbers would always have to be longs, this is because the `int.TryParse` method doesn't parse scientific notation but the `long.TryParse` method does. Unless we wanted to make additional changes in the `CompileNumber` function as well...

Let me know and I will start working on something.

**Comment by robert-mccausland** [comment]
Hi Thomas,

I've provided a pull request, let me know what you think.

**Comment by polterguy** [comment]
Luv it :)
