### ISSUE TITLE
Unreachable code in Compiler.CompileString()

### ISSUE THREAD

**Issue by SapphireBrand** [polterguy/lizzie#44]
There is a test for end-of-file in Compiler.CompileString which throws a parsing exception: `throw new LizzieParsingException($"Unexpected EOF after to '{stringConstant}'");` 

That code is unreachable because the tokenizer is responsible for balancing opening and closing braces, and it will throw if a closing brace is not seen.

You could delete it, change it to an assertion, or keep it as is.

**Comment by polterguy** [comment]
I assume you mean [this line in Tokenizer.cs](https://github.com/polterguy/lizzie/blob/4ce22d50fd1f3d09c4462c4c777604cc3864db72/lizzie/Tokenizer.cs#L190), right? This throws an exception if a string is never closed. Hence, the double check at the [following line](https://github.com/polterguy/lizzie/blob/4ce22d50fd1f3d09c4462c4c777604cc3864db72/lizzie/Compiler.cs#L272) can be modified to the following, right ...?

```
en.MoveNext();
```

I agree with you, and I have simplified the code, although in theory one might imagine alternative tokenizers, at which point it becomes an issue. However, since sanity checking string inputs arguably is the job of the tokenizer, I removed it anyway. It simplifies the code, works for 99.999% of all use cases, and for those it doesn't work with (alternative tokenizers), it's arguably the alternative tokenizer's job anyway to make sure strings are closed.
